sales_teaching_task:
  description: >
    Explain and teach ways of improving conversion rates for selling {topic}
    Make sure that your apprentices have a better understanding and tools to be successful in sales. It also rewards with a tip to his apprentice.
  expected_output: >
    Recommendations and assistance on the improvements the sales apprentice can do while selling {topic} . Also tipping his apprentice.
  agent: sales_rep_expert

sales_pitch_task:
  description: >
    Review and learn from the Sales Representative expert and excel at you sales pitch for selling {topic}
  expected_output: >
    A sales pitch about {topic} that carefully consider recommendation and teaching lessons from the expert.
    Formatted as markdown without '```'
  agent: sales_apprentice
